language: node_js
node_js: 
  - "stable"
  - "8"
  - "10"
  - "12"
env:
  - NODE_ENV=TEST_CI
services: mongodb
cache:
  directories:
    - "node_modules"
addons:
  hosts:
    - mongodb
before_script:
  - mongo FreeDay --eval 'db.createUser({user:"iv", pwd:"test", roles:["readWrite"]});'
before_install:
  - npm install .
script:
  - git checkout package-lock.json
  - npm test
deploy:
  provider: azure_web_apps
  on: master
  verbose: true
  username: $AZURE_USER
  password: $AZURE_PASSWORD
  site: $AZURE_SITE

