language: node_js
node_js: 
  - "stable"
  - "6"
  - "8"
  - "10"
  - "12"
services: mongodb
cache:
  directories:
    - "node_modules"
addons:
  hosts:
    - mongodb
before_script:
  - mongo FreeDay --eval 'db.createUser({user:"iv", pwd:"test", roles:["readWrite"]});'
before_install:
  - npm install .
script:
  - npm test

