version: "3.7"
services:
  nodeapp:
    image: node_app
    ports:
      - "80:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
    - "27017:27017"

