version: "3.7"
services:
  web:
    image: node_app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
    - "27017:27017"
