version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10
      - image: circleci/mongo
        -run:
          command: mongo FreeDay --eval 'db.createUser({user:"iv", pwd:"test", roles:["readWrite"]});'
        environment:
          - MONGO_INITDB_ROOT_USERNAME: "iv"
          - MONGO_INITDB_ROOT_PASSWORD: "test"
          - MONGO_URL: mongodb://127.0.0.1:27017
    working_directory: ~/IV
    steps:
      - checkout
      - run:
          name: Wait for Mongo
          command: dockerize -wait tcp:127.0.0.1:27017 -timeout 180s
      - run:
          name: Install package json dependencies
          command: npm install .
      - run:
          name: Run test
          command: npm test