version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10
      - image: circleci/mongo
    working_directory: ~/IV
    steps:
      - checkout
      - run:
          name: Install package json dependencies
          command: npm install .
      - run:
          name: Add mongodb to localhost
          command: |
            echo "127.0.0.1  mongodb" >> /etc/hosts
      - run:
          name: Run test
          command: npm test
