version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10
        environment:
          - MONGODB_USERNAME: "iv"
          - MONGODB_PASSWORD: "test"
          - MONGO_URL: mongodb://127.0.0.1:27017
    working_directory: ~/IV
    steps:
      - checkout
        - run:
          name: "MongoDB"
          command: |
            echo "deb http://repo.mongodb.org/apt/debian "$(lsb_release -sc)"/mongodb-org/4.0 main" | sudo tee /etc/apt/sources.list.d/mongodb.list
            sudo apt-get update
            sudo apt-get install mongodb-org
            mongo FreeDay --eval 'db.createUser({user:"iv", pwd:"test", roles:["readWrite"]});'
            mongo mongodb://localhost:27017 --eval "rs.initiate()"
      - run:
          name: Install package json dependencies
          command: npm install .
      - run:
          name: Run test
          command: npm test