version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10
      - image: circleci/mongo
        environment:
          - MONGODB_USERNAME: "iv"
          - MONGODB_PASSWORD: "test"
          - MONGO_URL: mongodb://127.0.0.1:27017
    working_directory: ~/IV
    steps:
      - checkout
      - run:
          name: Install package json dependencies
          command: npm install .
      - run:
          name: Run test
          command: npm test