# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.network "private_network", ip: "192.168.20.2"

  config.vm.hostname = "freeday"

  config.vm.provider "virtualbox" do |vb|
   vb.memory = "2048"
   vb.cpus = 2
   vb.name = "freeday"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.verbose  = "vvv"
  end
  
end
