version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/IV
    steps:
      - checkout
      - run:
          name: Install package json dependencies
          command: npm install .
      - run:
          name: Run test
          command: npm test